services:
  db:
    image: postgres:latest
    container_name: calorie_tracker_db
    environment:
      POSTGRES_USER: junkai
      POSTGRES_PASSWORD: junkai
      POSTGRES_DB: calorie_tracker
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: